### ISSUE TITLE
[TODO][BUG] Twitch bot will no longer connect to Twitch 

### ISSUE THREAD

**Issue by gbowne1** [gbowne1/newtwitchbot#1]
This is an update.

This project no longer connects to Twitch as a chat bot.  Though I can not gaurantee that it ever did connect at least correctly.

I expect to be able to use commands and do moderation.

I think this would be better as a community developed chat bot.  

I considered NodeJS, MongoDB/Mongoose, ExpressJS with a REACT frontend dashboard.

I built some stub code using some examples, but got lost with this project.  

Here are some initial ideas/goals that I for this bot.

- [ ] Notify on discord when streamer goes live
- [ ] Text to speech
- [ ] Stream Game 
- [ ] Trivia
- [ ] Song Request from Spotify
- [ ] Ban those pesky "wanna be famous.." bots

Here are some commands this bot will use

!project 

!today

!discord - Prints the Discord server invite link

!commands - Prints a list of commmands

!regulars - add

!shoutout (alias !so)

!socials (prints list of socials)

!uptime (prints stream uptime)

!followage (prints how long a user has follwed the channel)
